# Definition of the github action
# as per https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action

name: 'GitHub AutoMerge Action'
description: 'Automerge labeled GitHub Pull Requests.'

branding:
    icon: 'git-merge'
    color: 'green'

inputs:
    github_token:
        description: 'Token for the repo. Can be passed in using $\{{ secrets.GITHUB_TOKEN }}'
        required: true
    repository:
        description: 'Repository name to check. Default or empty value represents current github repository (${GITHUB_REPOSITORY})'
        default: ''
        required: false
    label:
        description: 'Label that indicates a pull request for merge.'
        required: false
        default: 'automerge'
    ignore_label:
        description: 'Label that forbids a merge.'
        required: false
        default: 'wip'
    options:
        description: 'Additional options (e.g. --dry-run)'
        required: false

runs:
    using: 'docker'
    image: 'Dockerfile'
